# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main", "develop", "feature/*" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: GitHub Action for SwiftLint (Only files changed in the PR)
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict
      env:
        DIFF_BASE: ${{ github.base_ref }}
